version: "3"
services:
  led_controller:
    restart: always
    build: .
    ports:
      - "8080:3000"
    environment:
      - APP_USERNAME=admin
      - APP_PASSWORD=password
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules